Code to import from sceptre
TKWWPublic/terraform-aws-ec2-autoscale-group pull request #1
Opened 2024-10-03 07:44 UTC by aballesta

## what

## why

## references

2024-10-07 13:11 UTC, Galofers requested changes

2024-10-07 13:11 UTC, Galofers commented on variables.tf
> +  default = ""
```suggestion
  default = ""
  description = "value of the id name for the launch template"
```

2024-10-07 13:11 UTC, Galofers approved these changes

2024-10-07 13:13 UTC, aballesta commented on variables.tf
> +  default = ""
done

2024-10-07 13:16 UTC, mpajuelofernandez approved these changes

2024-10-08 13:24 UTC, rdelgaizo commented
Should this be pointing to the devex_only branch?

2024-10-08 15:12 UTC, aballesta commented
> Should this be pointing to the devex_only branch?

I did changes to adapt the module to import all ASG from sceptre,  the idea for new ASG is continue using the cloudposse module not a fork

2024-10-09 08:12 UTC, rdelgaizo approved these changes

2024-10-11 08:08 UTC, merged